version: '3.9'

services:
  kong:
    build: .
    container_name: patricia-api-gateway
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_LISTEN: "0.0.0.0:8000 reuseport"
      KONG_LOG_LEVEL: warn

      JWT_SECRET: ${JWT_SECRET}

      URL_AUTH: ${URL_AUTH}
      URL_PROFILE: ${URL_PROFILE}
      URL_HANGOUT: ${URL_HANGOUT}
      URL_CHAT: ${URL_CHAT}
      URL_NOTIFICATION: ${URL_NOTIFICATION}
      URL_GAMIFICATION: ${URL_GAMIFICATION}
      URL_FEED_SEARCH: ${URL_FEED_SEARCH}
      URL_MATCHING: ${URL_MATCHING}
      URL_GEO: ${URL_GEO}
      URL_EVENTS: ${URL_EVENTS}
      URL_ANALYTICS: ${URL_ANALYTICS}
      URL_SUPPORT: ${URL_SUPPORT}

    ports:
      - "8000:8000"

    env_file: .env
